### ISSUE TITLE
Elm style compiler error messages

### ISSUE THREAD

**Issue by shmish111** [edwinb/Idris2-boot#21] opened 2019-07-17 15:53 UTC
If you've not seen Elm's compiler error messages they are simply awesome, check out https://elm-lang.org/blog/compiler-errors-for-humans

I think they very much fit in with the Idris philosophy of the compiler being your friend and guide rather than a gate keeper enemy. I was thinking, would the Idris compiler be capable of making suggestions based on the same mechanism used for type holes? For example if I have the following:
```idris
f : Int -> Int
f x = ?f_rhs
```
and I check the type of `?f_rhs` I get
```
Idris: Type of f_rhs
   x : Int
-------------------------------------
f_rhs : Int
```
Now consider an example where I implement `f` incorrectly
```idris
f : Int -> Int
f x = y
```
It would be nice if the compiler error message was something like
```
`y` is undefined

you need something of type Int and have the following terms available

   x : Int

perhaps you meant

  f x = x
```

Is this possible in theory? I was thinking of taking a look but I haven't looked at the code base yet, it's going to take a long while to get my head around it I think. Does anyone have any pointers on where to begin looking for this feature specifically?

**Comment by edwinb** [comment] 2019-07-17 17:02
In general, better error messages would be lovely to have (it's already listed in CONTRIBUTING.md as a thing to do), and many people have pointed me at Elm's error messages. I know they are lovely!

There's quite a bit to consider beyond this, though. For example, do you display normal forms of expressions, the exact form from the program, or some combination? Different situations might call for different things, and it might even be that the programmer should have some control. Or how about a situation where the clash is between two variables that happen to have the same name but are bound in different places and therefore are different, which can happen as a result of two functions with dependent types that have the same name for implicit arguments.

It would probably be better to post this sort of thing on the mailing list, and see if it can start a discussion on how to achieve it. At least for the moment, I'd prefer the issue tracker to be used for things where there's an objective answer as to when the issue is resolved. This is mostly about keeping my workload manageable (it is basically just me working on this in my work time at the moment after all). Perhaps we should consider using the currently empty wiki more actively for making and fleshing out proposals?

As for the technical question of how to achieve it - I think this will depend to some extent on how the IDE protocol develops. It seems plausible that a richer protocol would allow some kind of error message hooks that invoke the same expression search tactic that we already have. This will necessarily involve some deeper thought about how the IDE protocol works, so I'd rather not rush into it.

So, for all of those reasons, I'm going to close this - but please post to the mailing list, because I'm sure there'll be plenty of ideas.

**Closed as completed by edwinb** 2019-07-17 17:02 UTC
