### ISSUE TITLE
Can't solve constraint between: ?impty and elemType

### ISSUE THREAD

**Issue by JoeyEremondi** [edwinb/Idris2-boot#161] opened 2019-11-15 19:16 UTC
I'm hitting a weird bug for the implicit solver, where an unbound implicit seems to be treated differently than explicitly binding it with a 0-uses annotation. The error message doesn't say much about what's going on.

This code works fine in Idris 2:

```idris
data Container :  (tipe1 : Type) -> tipe1 -> Type where
    Base : Container Nat 0
    Pair : 
      (hpf: Container  elemType h ) ->
      Container (elemType, elemType) (h,h) 
```

But if we change it to explicitly bind its argument, it does not compile in Idris 2

```idris
data Container :  (tipe1 : Type) -> tipe1 -> Type where
    Base : Container Nat 0
    Pair : 
      {0 elemType : Type} ->
      (hpf: Container  elemType h ) ->
      Container (elemType, elemType) (h,h) 
```
gives 
```
While processing constructor Minimal2.Pair at Minimal2.idr:6:5--9:44:
Can't solve constraint between:
	?impty
and
	elemType

```

Both code snippets compile in Idris 1 (if your remove the linearity annotation, of course).

**Comment by edwinb** [comment] 2020-01-11 17:47
The reason it happens at the moment is that all unbound implicits are put before the bound implicits, so since `h : elemType`, and Idris decides to put `h` before the `elemType` binding (because that's what it always does), you get the error.

The error is bad, though, and it should probably accept the code anyway. I'll have a think.

**Comment by edwinb** [comment] 2020-01-11 20:29
I'm thinking that, for the sake of having the rules for implicits be as simple as possible (that is: all implicits are introduced at the top level of a type, so will be outside the scope of any foralls or other pi bindings), it's best if this *doesn't* type check.

The fact that it works in Idris 1 is more luck than judgement, I think. I'll have to document this difference, but for now I'll try to make the error message better and do more to explain what's going on (saying something like 'Can't infer type for implicit argument h', which is really what the problem is).

**Comment by edwinb** [comment] 2020-02-23 17:40
Since I've decided this is the correct behaviour (as in, simplest to explain the rules this way) for Idris 2, and the error message is at least a bit better now, I'm going to close this.

**Closed as completed by edwinb** 2020-02-23 17:40 UTC
