### ISSUE TITLE
Idris crashes with "Uncaught error: Error in TTC file: Corrupt TTC data for Name"

### ISSUE THREAD

**Issue by ohad** [edwinb/Idris2-boot#95] opened 2019-08-26 02:09 UTC
Work-in-progress:
I'm not sure how to debug this usefully, nor to minimize the program reproducing the bug. 
If anyone has any idea what might have caused it, I could try to minimise the program.

# Steps to Reproduce
This is a part of several modules, but the offending part is:
```
Additive_Nat : Model CMonoid_Th
Additive_Nat = Take Additive_Nat_Struct Nat_validate
where
  Nat_validate : let alg = Additive_Nat_Struct in
                 (eq : Equation (Sig CMonoid_Th)) -> 
                 Elem eq (Ax CMonoid_Th) ->  
                 (env : Fin (Context eq) -> U alg) -> (models MONOID alg eq) env
  Nat_validate eq eq_pos env with (name_cmonoid_axiom eq_pos)
    Nat_validate _ _ env |     Monoid_commutative = ?h1
    Nat_validate _ _ env | Mon Monoid_lft_neutral = ?h2
    Nat_validate _ _ env | Mon Monoid_rgt_neutral = ?h3
    Nat_validate _ _ env | Mon Monoid_associative = ?h4
```

# Expected Behavior
```
idris2 CMonoids.idr
8/8: Building CMonoids (CMonoids.idr)
Welcome to Idris 2 version 0.0. Enjoy yourself!
Main>
```
# Observed Behavior
```
$ idris2 CMonoids.idr
8/8: Building CMonoids (CMonoids.idr)
Uncaught error: Error in TTC file: Corrupt TTC data for Name
```
See [Additive_Nat.log](https://github.com/edwinb/Idris2/files/3539150/Additive_Nat.log) for a `%logging 3` inserted just before `Additive_Nat`.

**Comment by abailly** [comment] 2019-08-27 06:23
@ohad Out of pure curiosity for Idris2's internals, I would be interested in investigating this bug. Would you have a way to reproduce it somehow? I have vague ideas on how to investigate its origin but of course need to be able to run it for experimenting.

**Comment by ohad** [comment] 2019-08-27 09:12
OK, I'll try to minimise the program first.

Errors seem to depend on the filename and whether it is a module or not, and change based on file name:

In files without a `module` declaration:
```
8/8: Building foo (foo.idr)
Uncaught error: Error in TTC file: End of buffer when reading String
idris2 CMonoids.idr 
Uncaught error: Error in TTC file: End of buffer when reading String
idris2 Strange.idr 
8/8: Building Strange (Strange.idr)
Uncaught error: Error in TTC file: End of buffer when reading String
``` 

In files with a module declaration, the error depends on the file/module name:
```
8/8: Building Strange (Strange.idr)
Uncaught error: Error in TTC file: End of buffer when reading Binary
8/8: Building CMonoids (CMonoids.idr)
Uncaught error: Error in TTC file: Corrupt TTC data for Name
8/8: Building foo (foo.idr)
Uncaught error: Error in TTC file: End of buffer when reading String
```
It can also depend on a latent property, e.g., the length of the file contents.

**Comment by ohad** [comment] 2019-09-03 20:39
Simplifying somewhat, the error still happens with this fragment (+ quite a few other files!):
```
Nat_validate : (eq : Equation (Sig CMonoid_Th)) -> 
               Elem eq (Ax CMonoid_Th) ->  
               Bool
Nat_validate eq eq_pos with  (name_cmonoid_axiom eq_pos)
  Nat_validate _ _ |  (    Monoid_commutative) = True
  Nat_validate _ _ |  (Mon Monoid_lft_neutral) = True
  Nat_validate _ _ |  (Mon Monoid_rgt_neutral) = True
  Nat_validate _ _ |  (Mon Monoid_associative) = True
```

The error stays if we comment out the first line, but if we comment
out any other line, the other error disappears.

Systematically: 0 in the n-th place represents that line n was 
commented out:
```
0000 syntax error
0001 good
0010 good
0011 good
0100 good
0101 good
0110 good
0111 bad
1000 good
1001 good
1010 good
1011 good
1100 good
1101 good
1110 good
1111 bad
```
so the error is there only when all of the last 3 lines are present.

I'm running out of ideas how to simplify this code further.

**Comment by edwinb** [comment] 2019-09-21 11:26
Even if it can't be reduced further, it'd be useful to know where to look so I can try it out and try to spot anything in your code that might be unusual.

**Comment by edwinb** [comment] 2019-09-22 13:21
Since @ohad reports that this patch fixes the problem, I'll close this.

**Closed as completed by edwinb** 2019-09-22 13:21 UTC
